name             'jboss-deploy'
maintainer       'Janith Perera'
maintainer_email 'janith@member.fsf.org'
license          'All rights reserved'
description      'Deploy applications to Jboss-eap'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.4.0'
license          'GPLv3'
source_url	 'https://github.com/jantwisted/chef-jboss-deploy'
issues_url	 'https://github.com/jantwisted/chef-jboss-deploy'

supports 'redhat'
supports 'debian'
supports 'centos'
supports 'ubuntu'
